fix: Don't bail if AppLand server is not configured
applandinc/scanner pull request #112
Opened 2022-03-07 18:28 UTC by dividedmind

In cases where eg. API key is not configured, the message said that
online features would be skipped, but instead the scan failed anyway.

2022-03-07 18:49 UTC, dividedmind commented
@kgilpin or is it supposed to fail? The test (that now fails) and the warning message say different things.

2022-03-11 02:09 UTC, kgilpin commented
I think maybe we should change the doc rather than the app behavior. It would seem too strange to me as a user if the app behavior depends on whether I have an API key in my environment or not.

2022-03-11 17:00 UTC, kgilpin requested changes
On reflection, I think it might be best to change the doc to match current behavior. Trying to run in non-`all` mode without an API key should probably be considered an error. I don't think it's good for us to silently fall back on different behavior.

2022-03-17 16:36 UTC, kgilpin approved these changes

2022-03-17 16:36 UTC, merged

2022-03-17 17:02 UTC, appland-release commented
:tada: This PR is included in version 1.46.3 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@appland/scanner/v/1.46.3)
- [GitHub release](https://github.com/applandinc/scanner/releases/tag/v1.46.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: