doc: Document Findings and the finding hash
applandinc/scanner pull request #91
Opened 2022-01-26 19:48 UTC by kgilpin

2022-01-27 21:30 UTC, torchello commented on README.md
> +_Note_ The following fields are never included in the digest:
```suggestion
_Note:_ The following fields are never included in the digest:
```

2022-01-27 21:30 UTC, torchello commented on README.md
> +The digest is then the `sha256` of the content string, in hex.
It's not clear what is this `content string`? I'd assume the content contains all the properties listed below, but would be good to mention this explicitly.

2022-01-28 16:38 UTC, dividedmind commented
I still don't think it's a good idea to document the hash at all. It's one more place to update as we change it and it is an implementation detail. I think code (with possible comments) and tests should be enough of a documentation.

2022-01-28 16:40 UTC, dividedmind requested changes
I still don't think it's a good idea to document the hash at all. It's one more place to update as we change it and it is an implementation detail. I think code (with possible comments) and tests should be enough of a documentation. Doubly so that it lives in two different repositories.

As for the rest of the doc, looks good to me, thanks :)

2022-01-28 18:51 UTC, merged

2022-01-28 18:59 UTC, appland-release commented
:tada: This PR is included in version 1.39.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@appland/scanner/v/1.39.0)
- [GitHub release](https://github.com/applandinc/scanner/releases/tag/v1.39.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: